services:
  db:
    container_name: db
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - app_network


  backend:
    container_name: backend
    build: ./backend
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - media_data:/vol/web/media
      - log_data:/vol/web/logs
    depends_on:
      - db
    command:
      [
        "gunicorn",
        "config.wsgi:application",
        "--bind",
        "0.0.0.0:3000",
        "--workers",
        "3",
        "--threads",
        "2",
        "--timeout",
        "60"
      ]
    restart: unless-stopped
    networks:
      - app_network


  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - media_data:/vol/web/media
      - log_data:/vol/web/logs
      - certificates_data:/etc/nginx/certs
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app_network


volumes:
  postgres_data:
  media_data:
  log_data:
  certificates_data:


networks:
  app_network:
    driver: bridge