# Generated by Django 6.0.3 on 2026-03-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Automação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Automação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('manual_time', models.BigIntegerField(blank=True, null=True, verbose_name='Tempo Manual (seg)')),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
                'db_table': 'automations',
                'ordering': ['-created_at'],
            },
        ),
    ]
