# Generated by Django 6.0.3 on 2026-03-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Automação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Automação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('manual_time', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Tempo Manual (seg)')),
                ('execution_cost', models.DecimalField(blank=True, db_comment='Campo para armazenar o custo estimado de execução da automação o custo deve ser calculado com base na etapa da execução', decimal_places=2, max_digits=10, null=True, verbose_name='Custo de Execução')),
                ('in_manutention', models.BooleanField(db_comment='Indica se a automação está em manutenção, ou seja, não deve ser executada', default=True, verbose_name='Em Manutenção')),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
                'db_table': 'automations',
                'ordering': ['-created_at'],
            },
        ),
    ]
