# Generated by Django 6.0.3 on 2026-03-20 14:13

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Automação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Automação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('manual_time', models.BigIntegerField(verbose_name='Tempo Manual (seg)')),
                ('in_manutention', models.BooleanField(db_comment='Indica se a automação está em manutenção, ou seja, não deve ser executada', default=True, verbose_name='Em Manutenção')),
                ('auth_certificate', models.BooleanField(db_comment='Autentica com Certificado?', default=True, verbose_name='Autentica com Certificado?')),
                ('url_certificate', models.URLField(blank=True, db_comment='Url usada para efetuar a autenticação de certificados automaticamente.', null=True, verbose_name='Url de troca de certificado')),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
                'db_table': 'automations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAutomation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Automação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Automação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('manual_time', models.BigIntegerField(verbose_name='Tempo Manual (seg)')),
                ('in_manutention', models.BooleanField(db_comment='Indica se a automação está em manutenção, ou seja, não deve ser executada', default=True, verbose_name='Em Manutenção')),
                ('auth_certificate', models.BooleanField(db_comment='Autentica com Certificado?', default=True, verbose_name='Autentica com Certificado?')),
                ('url_certificate', models.URLField(blank=True, db_comment='Url usada para efetuar a autenticação de certificados automaticamente.', null=True, verbose_name='Url de troca de certificado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Automação',
                'verbose_name_plural': 'historical Automações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
