# Generated by Django 6.0.3 on 2026-03-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_initial'),
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='departments.department', verbose_name='Departamento'),
        ),
    ]
