# Generated by Django 6.0.3 on 2026-03-20 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0003_initial'),
        ('departments', '0001_initial'),
        ('positions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_automations', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AddField(
            model_name='historicalautomation',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='historicalautomation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalautomation',
            name='position',
            field=models.ForeignKey(blank=True, db_comment='Campo para armazenar o cargo associado à automação, o cargo deve ser utilizado para calcular o custo de execução da automação com base no custo por hora do cargo e no tempo estimado de execução da automação', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='positions.position', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='historicalautomation',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
    ]
