# Generated by Django 6.0.3 on 2026-03-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_historicalautomation'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='position',
            field=models.ForeignKey(blank=True, db_comment='Campo para armazenar o cargo associado à automação, o cargo deve ser utilizado para calcular o custo de execução da automação com base no custo por hora do cargo e no tempo estimado de execução da automação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='positions.position', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='historicalautomation',
            name='position',
            field=models.ForeignKey(blank=True, db_comment='Campo para armazenar o cargo associado à automação, o cargo deve ser utilizado para calcular o custo de execução da automação com base no custo por hora do cargo e no tempo estimado de execução da automação', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='positions.position', verbose_name='Cargo'),
        ),
    ]
