# Generated by Django 6.0.3 on 2026-03-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_alter_automation_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='execution_cost',
            field=models.DecimalField(blank=True, db_comment='Campo para armazenar o custo estimado de execução da automação o custo deve ser calculado com base na etapa da execução', decimal_places=2, max_digits=10, null=True, verbose_name='Custo de Execução'),
        ),
        migrations.AddField(
            model_name='automation',
            name='in_manutention',
            field=models.BooleanField(db_comment='Indica se a automação está em manutenção, ou seja, não deve ser executada', default=True, verbose_name='Em Manutenção'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='manual_time',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Tempo Manual (seg)'),
        ),
    ]
