# Generated by Django 6.0.3 on 2026-03-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0005_automation_position_historicalautomation_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='execution_cost',
        ),
        migrations.RemoveField(
            model_name='historicalautomation',
            name='execution_cost',
        ),
    ]
