# Generated by Django 6.0.3 on 2026-03-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0006_remove_automation_execution_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='manual_time',
            field=models.BigIntegerField(default=0, verbose_name='Tempo Manual (seg)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalautomation',
            name='manual_time',
            field=models.BigIntegerField(default=30, verbose_name='Tempo Manual (seg)'),
            preserve_default=False,
        ),
    ]
