# Redireciona HTTP para HTTPS
server {
    listen 80;
    server_name _;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/certs/django_backend.crt;
    ssl_certificate_key /etc/nginx/certs/django_backend.key;

    # FRONTEND (React build) - Caminho para onde a build do react está localizada
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }

    # BACKEND API - Proxy para o backend Django rodando na porta 3000 do container "backend"
    location /api/ {
        proxy_pass http://backend:3000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # MEDIA DJANGO - Caminho para os arquivos de mídia do Django
    location /media/ {
        alias /vol/web/media/;
    }

    # LOGS - Caminho para os arquivos de logs do Django
    location /logs/ {
        alias /vol/web/logs/;
    }
}