# Generated by Django 6.0.3 on 2026-03-20 14:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Data de inicio')),
                ('date_end', models.DateTimeField(blank=True, db_comment='Data fim da execução, preenchida quando a execução for finalizada (Sucesso ou Alerta)', null=True, verbose_name='Data de fim')),
                ('cost_hour', models.DecimalField(blank=True, db_comment='Custo hora do cargo especificado na automação', decimal_places=2, max_digits=10, null=True, verbose_name='Custo de Execução')),
                ('step_time', models.IntegerField(db_comment='Tempo manual que o humano leva para executar a etapa', default=0)),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('concluido', 'Concluido'), ('erro', 'Erro'), ('alerta', 'Alerta'), ('teste', 'Teste')], max_length=10, verbose_name='Status')),
                ('step_counts', models.IntegerField(db_comment='Contagem de Etapas', default=0, verbose_name='Contagem de Etapas')),
                ('success_count', models.IntegerField(db_comment='Contagem de Sucesso das etapas', default=0, verbose_name='Contagem de Sucesso das etapas')),
                ('error_count', models.IntegerField(blank=True, db_comment='Contagem de Erros das etapas', default=0, verbose_name='Contagem de Erros das etapas')),
                ('time_automation_seconds', models.IntegerField(db_comment='Total de tempo acumulado das etapas que registraram date_end(Sucesso ou Alerta)', default=0, verbose_name='Tempo de execução da automação em segundos')),
                ('time_manual_seconds', models.IntegerField(db_comment='Total de tempo acumulado das etapas que registraram date_end(Sucesso ou Alerta)', default=0, verbose_name='Tempo de execução manual em segundos')),
                ('time_economy_seconds', models.IntegerField(db_comment='Total de tempo economizado das etapas que registraram date_end(Sucesso ou Alerta) - (time_automation_seconds - time_manual_seconds)', default=0, verbose_name='Tempo economizado em segundos')),
                ('cost_economy', models.DecimalField(db_comment='Economia de custo', decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Economia de custo')),
                ('potential_time_seconds', models.IntegerField(db_comment='Total de tempo acumulado que foi automatizado do processo humano', default=0, verbose_name='Tempo potencial economizado (seg)')),
                ('potential_cost', models.DecimalField(db_comment='Custo potencial economizado - Total de tempo acumulado que foi automatizado do processo humano * custo hora do cargo especificado na automação', decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Custo potencial economizado')),
                ('efficiency_percent', models.DecimalField(db_comment='Eficiencia da automação em relação ao processo humano', decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Eficiência (%)')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='automations.automation', verbose_name='Automação')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='business.business', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Execução',
                'verbose_name_plural': 'Execuções',
                'db_table': 'executions',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='executions.execution', verbose_name='Execução')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificação')),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('concluido', 'Concluido'), ('erro', 'Erro'), ('alerta', 'Alerta'), ('teste', 'Teste')], max_length=10, verbose_name='Status')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Data de inicio')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Data de fim')),
                ('time_automation_seconds', models.IntegerField(default=0, verbose_name='Tempo de execução da automação em segundos')),
                ('time_manual_seconds', models.IntegerField(default=0, verbose_name='Tempo de execução manual em segundos')),
                ('time_economy_seconds', models.IntegerField(default=0, verbose_name='Tempo de economia em segundos')),
                ('potential_time_seconds', models.IntegerField(default=0, verbose_name='Tempo potencial economizado (seg)')),
                ('potential_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Custo potencial economizado')),
                ('efficiency_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Eficiência (%)')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='executions.execution', verbose_name='Execução')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'steps',
                'ordering': ['-date_start'],
            },
        ),
    ]
