# Generated by Django 6.0.3 on 2026-03-14 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Data de inicio')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Data de fim')),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('concluido', 'Concluido'), ('erro', 'Erro'), ('alerta', 'Alerta')], max_length=10, verbose_name='Status')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automations.automation', verbose_name='Automação')),
            ],
            options={
                'verbose_name': 'Execução',
                'verbose_name_plural': 'Execuções',
                'db_table': 'executions',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='executions.execution', verbose_name='Execução')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificação')),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('concluido', 'Concluido'), ('erro', 'Erro'), ('alerta', 'Alerta')], max_length=10, verbose_name='Status')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Data de inicio')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Data de fim')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='executions.execution', verbose_name='Execução')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'steps',
                'ordering': ['-date_start'],
            },
        ),
    ]
