# Generated by Django 6.0.3 on 2026-03-18 20:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Data de inicio')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Data de fim')),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('concluido', 'Concluido'), ('erro', 'Erro'), ('alerta', 'Alerta'), ('teste', 'Teste')], default='iniciado', max_length=10, verbose_name='Status')),
                ('step_counts', models.IntegerField(blank=True, default=0, null=True, verbose_name='Contagem de Etapas')),
                ('success_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Contagem de Sucesso')),
                ('error_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Contagem de Erros')),
                ('time_automation_seconds', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo de execução da automação em segundos')),
                ('time_manual_seconds', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo de execução manual em segundos')),
                ('time_economy_seconds', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo economizado em segundos')),
                ('cost_economy', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Economia de custo')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automations.automation', verbose_name='Automação')),
            ],
            options={
                'verbose_name': 'Execução',
                'verbose_name_plural': 'Execuções',
                'db_table': 'executions',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='executions.execution', verbose_name='Execução')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificação')),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('concluido', 'Concluido'), ('erro', 'Erro'), ('alerta', 'Alerta'), ('teste', 'Teste')], max_length=10, verbose_name='Status')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Data de inicio')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Data de fim')),
                ('time_automation_seconds', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo de execução da automação em segundos')),
                ('time_manual_seconds', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo de execução manual em segundos')),
                ('time_economy_seconds', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo de economia em segundos')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='executions.execution', verbose_name='Execução')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'steps',
                'ordering': ['-date_start'],
            },
        ),
    ]
