# Generated by Django 6.0.3 on 2026-03-19 08:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='efficiency_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eficiência (%)'),
        ),
        migrations.AddField(
            model_name='execution',
            name='potential_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Custo potencial economizado'),
        ),
        migrations.AddField(
            model_name='execution',
            name='potential_time_seconds',
            field=models.IntegerField(default=0, verbose_name='Tempo potencial economizado (seg)'),
        ),
        migrations.AddField(
            model_name='step',
            name='efficiency_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eficiência (%)'),
        ),
        migrations.AddField(
            model_name='step',
            name='potential_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Custo potencial economizado'),
        ),
        migrations.AddField(
            model_name='step',
            name='potential_time_seconds',
            field=models.IntegerField(default=0, verbose_name='Tempo potencial economizado (seg)'),
        ),
    ]
