# Generated by Django 6.0.3 on 2026-03-23 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='executions.execution', verbose_name='Execução'),
        ),
        migrations.AlterField(
            model_name='step',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='executions.execution', verbose_name='Execução'),
        ),
    ]
