# Generated by Django 6.0.3 on 2026-03-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_alter_log_execution_alter_step_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='step_counts',
            field=models.IntegerField(default=0, verbose_name='Contagem de Etapas'),
        ),
        migrations.AddField(
            model_name='execution',
            name='success_count',
            field=models.IntegerField(default=0, verbose_name='Contagem de Sucesso'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('concluido', 'Concluido'), ('erro', 'Erro'), ('alerta', 'Alerta')], default='iniciado', max_length=10, verbose_name='Status'),
        ),
    ]
