# Generated by Django 6.0.3 on 2026-03-19 08:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_execution_efficiency_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='cost_economy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Economia de custo'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='efficiency_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Eficiência (%)'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='time_automation_seconds',
            field=models.IntegerField(default=0, verbose_name='Tempo de execução da automação em segundos'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='time_economy_seconds',
            field=models.IntegerField(default=0, verbose_name='Tempo economizado em segundos'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='time_manual_seconds',
            field=models.IntegerField(default=0, verbose_name='Tempo de execução manual em segundos'),
        ),
        migrations.AlterField(
            model_name='step',
            name='efficiency_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Eficiência (%)'),
        ),
        migrations.AlterField(
            model_name='step',
            name='time_automation_seconds',
            field=models.IntegerField(default=0, verbose_name='Tempo de execução da automação em segundos'),
        ),
        migrations.AlterField(
            model_name='step',
            name='time_economy_seconds',
            field=models.IntegerField(default=0, verbose_name='Tempo de economia em segundos'),
        ),
        migrations.AlterField(
            model_name='step',
            name='time_manual_seconds',
            field=models.IntegerField(default=0, verbose_name='Tempo de execução manual em segundos'),
        ),
    ]
