# Generated by Django 6.0.3 on 2026-03-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_alter_log_execution_alter_step_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
    ]
