# Generated by Django 6.0.3 on 2026-03-19 09:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_alter_execution_cost_economy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='efficiency_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Eficiência (%)'),
        ),
        migrations.AlterField(
            model_name='step',
            name='efficiency_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Eficiência (%)'),
        ),
    ]
