# Generated by Django 6.0.3 on 2026-03-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_execution_step_counts_execution_success_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='step_counts',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Contagem de Etapas'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='success_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Contagem de Sucesso'),
        ),
    ]
