# Generated by Django 6.0.3 on 2026-03-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_initial'),
        ('executions', '0004_alter_execution_efficiency_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='automations.automation', verbose_name='Automação'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='error_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Contagem de Erros'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='step_counts',
            field=models.IntegerField(default=0, verbose_name='Contagem de Etapas'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='success_count',
            field=models.IntegerField(default=0, verbose_name='Contagem de Sucesso'),
        ),
        migrations.AlterField(
            model_name='log',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='executions.execution', verbose_name='Execução'),
        ),
        migrations.AlterField(
            model_name='step',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='executions.execution', verbose_name='Execução'),
        ),
    ]
