# Generated by Django 6.0.3 on 2026-03-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0004_alter_execution_step_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='error_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Contagem de Erros'),
        ),
    ]
