# Generated by Django 6.0.3 on 2026-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0005_execution_error_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='cost_economy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Economia de custo'),
        ),
        migrations.AddField(
            model_name='execution',
            name='time_automation_seconds',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo de execução da automação em segundos'),
        ),
        migrations.AddField(
            model_name='execution',
            name='time_economy_seconds',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo economizado em segundos'),
        ),
        migrations.AddField(
            model_name='execution',
            name='time_manual_seconds',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo de execução manual em segundos'),
        ),
        migrations.AddField(
            model_name='step',
            name='time_automation_seconds',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo de execução da automação em segundos'),
        ),
        migrations.AddField(
            model_name='step',
            name='time_economy_seconds',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo de economia em segundos'),
        ),
        migrations.AddField(
            model_name='step',
            name='time_manual_seconds',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo de execução manual em segundos'),
        ),
    ]
