# Generated by Django 6.0.3 on 2026-03-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0005_alter_execution_automation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='cost_hour',
            field=models.DecimalField(blank=True, db_comment='Custo hora do cargo especificiado na automação', decimal_places=2, max_digits=10, null=True, verbose_name='Custo de Execução'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('concluido', 'Concluido'), ('erro', 'Erro'), ('alerta', 'Alerta'), ('teste', 'Teste')], max_length=10, verbose_name='Status'),
        ),
    ]
