# Generated by Django 6.0.3 on 2026-03-18 16:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0006_execution_cost_economy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='cost_economy',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Economia de custo'),
        ),
    ]
