# Generated by Django 6.0.3 on 2026-03-19 22:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0006_execution_cost_hour_alter_execution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='step_time',
            field=models.IntegerField(db_comment='Tempo manual que o humano leva para executar a etapa', default=0),
        ),
        migrations.AlterField(
            model_name='execution',
            name='cost_economy',
            field=models.DecimalField(db_comment='Economia de custo', decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Economia de custo'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='cost_hour',
            field=models.DecimalField(blank=True, db_comment='Custo hora do cargo especificado na automação', decimal_places=2, max_digits=10, null=True, verbose_name='Custo de Execução'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='date_end',
            field=models.DateTimeField(blank=True, db_comment='Data fim da execução, preenchida quando a execução for finalizada (Sucesso ou Alerta)', null=True, verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='efficiency_percent',
            field=models.DecimalField(db_comment='Eficiencia da automação em relação ao processo humano', decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Eficiência (%)'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='error_count',
            field=models.IntegerField(blank=True, db_comment='Contagem de Erros das etapas', default=0, verbose_name='Contagem de Erros das etapas'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='potential_cost',
            field=models.DecimalField(db_comment='Custo potencial economizado - Total de tempo acumulado que foi automatizado do processo humano * custo hora do cargo especificado na automação', decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Custo potencial economizado'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='potential_time_seconds',
            field=models.IntegerField(db_comment='Total de tempo acumulado que foi automatizado do processo humano', default=0, verbose_name='Tempo potencial economizado (seg)'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='step_counts',
            field=models.IntegerField(db_comment='Contagem de Etapas', default=0, verbose_name='Contagem de Etapas'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='success_count',
            field=models.IntegerField(db_comment='Contagem de Sucesso das etapas', default=0, verbose_name='Contagem de Sucesso das etapas'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='time_automation_seconds',
            field=models.IntegerField(db_comment='Total de tempo acumulado das etapas que registraram date_end(Sucesso ou Alerta)', default=0, verbose_name='Tempo de execução da automação em segundos'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='time_economy_seconds',
            field=models.IntegerField(db_comment='Total de tempo economizado das etapas que registraram date_end(Sucesso ou Alerta) - (time_automation_seconds - time_manual_seconds)', default=0, verbose_name='Tempo economizado em segundos'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='time_manual_seconds',
            field=models.IntegerField(db_comment='Total de tempo acumulado das etapas que registraram date_end(Sucesso ou Alerta)', default=0, verbose_name='Tempo de execução manual em segundos'),
        ),
    ]
