# Generated by Django 6.0.3 on 2026-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Negócio')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/', verbose_name='Logo do Negócio')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='business_certificados/', verbose_name='Certificado Digital')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Negócio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('certificate_expire', models.DateTimeField(blank=True, null=True)),
                ('subject_cn', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_c', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_o', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_cn', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_c', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_o', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Negócio',
                'verbose_name_plural': 'Negócios',
                'db_table': 'business',
            },
        ),
    ]
