# Generated by Django 6.0.3 on 2026-03-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
