# Generated by Django 6.0.3 on 2026-03-19 17:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('junior', 'Junior'), ('pleno', 'Pleno'), ('senior', 'Senior'), ('supervisor', 'Supervisor'), ('gerencia', 'Gerência'), ('diretoria', 'Diretoria')], max_length=50)),
                ('cost_hour', models.DecimalField(blank=True, db_comment='Campo para armazenar o custo por hora do cargo', decimal_places=2, max_digits=10, null=True, verbose_name='Custo por Hora')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'positions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPosition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('junior', 'Junior'), ('pleno', 'Pleno'), ('senior', 'Senior'), ('supervisor', 'Supervisor'), ('gerencia', 'Gerência'), ('diretoria', 'Diretoria')], max_length=50)),
                ('cost_hour', models.DecimalField(blank=True, db_comment='Campo para armazenar o custo por hora do cargo', decimal_places=2, max_digits=10, null=True, verbose_name='Custo por Hora')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cargo',
                'verbose_name_plural': 'historical Cargos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
